name: zaha_application
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+1.0.1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences:
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  intl: ^0.16.1
  google_fonts: ^0.3.5
  font_awesome_flutter:
  intro_views_flutter: ^2.8.0
  flutter_cache_manager: ^1.1.3
  cached_network_image: ^2.0.0
  google_sign_in: ^4.5.1
  flutter_swiper: ^1.1.6
  animated_text_kit: ^2.0.0
  carousel_pro: ^0.0.13
  url_launcher: ^5.5.0
  flutter_open_whatsapp: ^0.1.2
  motion_tab_bar: ^0.1.1
  google_nav_bar: ^2.2.0
  http: ^0.12.1
  firebase_auth: ^0.16.1
  flutter_facebook_login: ^3.0.0
  flutter_launcher_icons: ^0.7.5
  connectivity: ^0.4.9
  mailto: ^0.2.0+1
  apple_sign_in: ^0.1.0
  flappy_search_bar: ^1.7.2
  giffy_dialog: ^1.8.0
  pin_code_text_field: ^1.6.0
  email_validator: ^1.0.5
  picker: ^1.0.6
  getwidget: ^1.1.3
  multiselect_formfield: ^0.1.4
  multi_image_picker: ^4.7.14
  responsive_grid: ^1.2.1+1
  flutter_absolute_path: ^1.0.6
  http_parser: ^3.1.4
  dependencies:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_launcher_icons: ^0.7.5

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  image_path_ios: "assets/icon/icon.png"

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/img/
    - assets/img/avatar.png
    - assets/img/customer-service.png
    - assets/img/bg.jpg
    - assets/img/zaha.png
    - assets/img/logo.png
    - assets/img/cover.jpg
    - assets/img/bg1.jpg
    - assets/img/logo1.png
    - assets/img/bg3.jpg
    - assets/img/profile.png

  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/hacentunisia.ttf


